language: python
python:
  - "2.7"

os: linux
dist: trusty
# Short duration job, use the container/without sudo image as it boots faster
sudo: false
# Use the latest Travis images since they are more up to date than the stable release.
group: edge

before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log # erase log

cache:
  directories:
    - "~/.platformio"
    - $HOME/.cache/pip # pip cache

env:
  global:
   # Warnings are errors
   - PLATFORMIO_BUILD_FLAGS="-Werror -Wno-error=deprecated-declarations"

matrix:
  fast_finish: true
  include:
    - env: BOARD=uno PLATFORMIO_CI_SRC=examples/RTU/ModbusRTUClientKitchenSink
    - env: BOARD=uno PLATFORMIO_CI_SRC=examples/RTU/ModbusRTUClientToggle
    - env: BOARD=uno PLATFORMIO_CI_SRC=examples/RTU/ModbusRTUServerKitchenSink
    - env: BOARD=uno PLATFORMIO_CI_SRC=examples/RTU/ModbusRTUServerLED
    - env: BOARD=uno PLATFORMIO_CI_SRC=examples/RTU/ModbusRTUTemperatureSensor

    - env: BOARD=diecimilaatmega328 PLATFORMIO_CI_SRC=examples/RTU/ModbusRTUClientKitchenSink
    - env: BOARD=diecimilaatmega328 PLATFORMIO_CI_SRC=examples/RTU/ModbusRTUClientToggle
    - env: BOARD=diecimilaatmega328 PLATFORMIO_CI_SRC=examples/RTU/ModbusRTUServerKitchenSink
    - env: BOARD=diecimilaatmega328 PLATFORMIO_CI_SRC=examples/RTU/ModbusRTUServerLED
    - env: BOARD=diecimilaatmega328 PLATFORMIO_CI_SRC=examples/RTU/ModbusRTUTemperatureSensor

    - env: BOARD=pro16MHzatmega328 PLATFORMIO_CI_SRC=examples/RTU/ModbusRTUClientKitchenSink
    - env: BOARD=pro16MHzatmega328 PLATFORMIO_CI_SRC=examples/RTU/ModbusRTUClientToggle
    - env: BOARD=pro16MHzatmega328 PLATFORMIO_CI_SRC=examples/RTU/ModbusRTUServerKitchenSink
    - env: BOARD=pro16MHzatmega328 PLATFORMIO_CI_SRC=examples/RTU/ModbusRTUServerLED
    - env: BOARD=pro16MHzatmega328 PLATFORMIO_CI_SRC=examples/RTU/ModbusRTUTemperatureSensor

    - env: BOARD=due PLATFORMIO_CI_SRC=examples/RTU/ModbusRTUClientKitchenSink
    - env: BOARD=due PLATFORMIO_CI_SRC=examples/RTU/ModbusRTUClientToggle
    - env: BOARD=due PLATFORMIO_CI_SRC=examples/RTU/ModbusRTUServerKitchenSink
    - env: BOARD=due PLATFORMIO_CI_SRC=examples/RTU/ModbusRTUServerLED
    - env: BOARD=due PLATFORMIO_CI_SRC=examples/RTU/ModbusRTUTemperatureSensor

    - env: BOARD=mkrwifi1010 PLATFORMIO_CI_SRC=examples/RTU/ModbusRTUClientKitchenSink
    - env: BOARD=mkrwifi1010 PLATFORMIO_CI_SRC=examples/RTU/ModbusRTUClientToggle
    - env: BOARD=mkrwifi1010 PLATFORMIO_CI_SRC=examples/RTU/ModbusRTUServerKitchenSink
    - env: BOARD=mkrwifi1010 PLATFORMIO_CI_SRC=examples/RTU/ModbusRTUServerLED
    - env: BOARD=mkrwifi1010 PLATFORMIO_CI_SRC=examples/RTU/ModbusRTUTemperatureSensor
    - env: BOARD=mkrwifi1010 PLATFORMIO_CI_SRC=examples/TCP/WiFiModbusClientToggle
    - env: BOARD=mkrwifi1010 PLATFORMIO_CI_SRC=examples/TCP/WiFiModbusServerLED

    - os: linux
      dist: trusty
      # Short duration job, would use the container/without sudo image as it boots faster, but we need a backported lintian, so don't
      sudo: required
      env: TASK='spellintian'
      addons:
        apt:
          packages:
           - moreutils
    - os: linux
      dist: trusty
      # Short duration job, would use the container/without sudo image as it boots faster, but we need a backported lintian, so don't
      sudo: required
      env: TASK='spellintian-duplicates'
      addons:
        apt:
          packages:
           - moreutils
    - os: linux
      dist: trusty
      env: TASK='codespell'
      addons:
        apt:
          packages:
           - moreutils

  allow_failures:
    - os: linux
      dist: trusty
      env: TASK='spellintian-duplicates'

before_install:
 - if [ "$TASK" == "spellintian" -o "$TASK" == "spellintian-duplicates" ]; then sudo add-apt-repository ppa:waja/trusty-backports -y; sudo apt-get update -qq; sudo apt-get install lintian -y; fi # Install a late enough lintian

install:
  - if [ -z "$TASK" ]; then pip install --upgrade platformio; fi
  - if [ -z "$TASK" ]; then platformio lib install "ArduinoRS485"; fi
  - if [ -z "$TASK" -a "$BOARD" == "mkrwifi1010" ]; then platformio lib install "WiFiNINA"; fi
  - if [ "$TASK" = "codespell" ]; then pip install --upgrade git+https://github.com/codespell-project/codespell.git; fi

script:
  - bash -ex .travis-ci.sh
