name: Compile Examples

on:
  pull_request:
    paths:
      - ".github/workflows/compile-examples.yml"
      - "library.properties"
      - "examples/**"
      - "src/**"
  push:
    paths:
      - ".github/workflows/compile-examples.yml"
      - "library.properties"
      - "examples/**"
      - "src/**"
  schedule:
    # run every Tuesday at 3 AM UTC to catch breakage caused by changes to external dependencies (libraries, platforms)
    - cron: "0 3 * * 2"
  # See: https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows#workflow_dispatch
  workflow_dispatch:

env:
  SKETCHES_REPORTS_PATH: sketches-reports

jobs:
  compile:
    name: ${{ matrix.board.fqbn }}
    runs-on: ubuntu-latest

    env:
      # Libraries to install for all boards
      UNIVERSAL_LIBRARIES: |
        # Install the ArduinoModbus library from the local path
        - source-path: ./
        - name: ArduinoRS485
      UNIVERSAL_SKETCH_PATHS: |
        - examples/RTU

    strategy:
      fail-fast: false

      matrix:
        board:
          - fqbn: arduino:megaavr:uno2018:mode=off
            ethernet: true
            nina: true
            artifact-name-suffix: arduino-megaavr-uno2018
          - fqbn: arduino:samd:mkrwifi1010
            ethernet: true
            nina: true
            artifact-name-suffix: arduino-samd-mkrwifi1010
          - fqbn: arduino:mbed_nano:nano33ble
            ethernet: false
            nina: false
            artifact-name-suffix: arduino-mbed_nano-nano33ble
          - fqbn: arduino:mbed_portenta:envie_m7
            ethernet: false
            nina: false
            artifact-name-suffix: arduino-mbed_portenta-envie_m7
          - fqbn: arduino:mbed_opta:opta
            ethernet: true
            nina: false
            artifact-name-suffix: arduino-mbed_opta-opta

        # Make board type-specific customizations to the matrix jobs
        include:
          - board:
              # Boards with Ethernet library support
              ethernet: true
            # Install these libraries in addition to the ones defined by env.UNIVERSAL_LIBRARIES
            ethernet-libraries: |
              - name: Ethernet
            # Compile these sketches in addition to the ones defined by env.UNIVERSAL_SKETCH_PATHS
            ethernet-sketch-paths: |
              - examples/TCP/EthernetModbusClientToggle
              - examples/TCP/EthernetModbusServerLED
          - board:
              ethernet: false
            ethernet-libraries: ""
            ethernet-sketch-paths: ""
          - board:
              # Boards with NINA-W102 module
              nina: true
            # Install these libraries in addition to the ones defined by env.UNIVERSAL_LIBRARIES
            nina-libraries: |
              - name: WiFiNINA
            # Compile these sketches in addition to the ones defined by env.UNIVERSAL_SKETCH_PATHS
            nina-sketch-paths: |
              - examples/TCP/WiFiModbusClientToggle
              - examples/TCP/WiFiModbusServerLED
          - board:
              nina: false
            nina-libraries: ""
            nina-sketch-paths: ""

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Compile examples
        uses: arduino/compile-sketches@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          fqbn: ${{ matrix.board.fqbn }}
          libraries: |
            ${{ env.UNIVERSAL_LIBRARIES }}
            ${{ matrix.ethernet-libraries }}
            ${{ matrix.nina-libraries }}
          sketch-paths: |
            ${{ env.UNIVERSAL_SKETCH_PATHS }}
            ${{ matrix.ethernet-sketch-paths }}
            ${{ matrix.nina-sketch-paths }}
          enable-deltas-report: true
          sketches-report-path: ${{ env.SKETCHES_REPORTS_PATH }}

      - name: Save memory usage change report as artifact
        uses: actions/upload-artifact@v4
        with:
          if-no-files-found: error
          name: sketches-report-${{ matrix.board.artifact-name-suffix }}
          path: ${{ env.SKETCHES_REPORTS_PATH }}

  report:
    needs: compile
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest

    steps:
      - name: Download sketches reports artifacts
        uses: actions/download-artifact@v4
        with:
          path: ${{ env.SKETCHES_REPORTS_PATH }}

      - uses: arduino/report-size-deltas@v1
        with:
          sketches-reports-source: ${{ env.SKETCHES_REPORTS_PATH }}
